### PR TITLE
support config.sass.load_paths

### PR DESCRIPTION
**Pull request by dreyks**
I have some concerns about the usage of construction `&method(:safe_merge)`. It looks nice, but I've heard that it's slower than calling a block. Do you have some performance tests?

### CODE REVIEW

**Comment by mibamur** [comment]
@dreyks https://github.com/JuanitoFatas/fast-ruby#normal-way-to-apply-method-vs-method-code

**Comment by dreyks** [comment]
riight... I'll redo this less fancy but more performant way, thanks

**Comment by dreyks** [comment]
ping @bolandrm

**Comment by patleb** [comment]
is there a reason this is not merged yet?

**Comment by dreyks** [comment]
rebased on top of current master branch

**Comment by bolandrm** [comment]
@dreyks looks like there are some tests failing

**Comment by dreyks** [comment]
huh... they were all green before the rebase. I'll check this out

**Comment by bolandrm** [comment]
it could also be an issue with master

**Comment by dreyks** [comment]
yeah the failures are exactly same as for the clean master branch

https://travis-ci.org/sass/sassc-rails/builds/143164248

**Comment by dreyks** [comment]
So ~~call~~ merge me maybe? :D

**Comment by patleb** [comment]
thx!

**Pull request merged**
