### PR TITLE
Add sass/scss generators

### PR DESCRIPTION
**Pull request by itkrt2y**
ref https://github.com/sass/sassc-rails/issues/74

This is just copies of [rails/sass-rails](https://github.com/rails/sass-rails/)'s generators.
But this works correctly.

### CODE REVIEW

**Comment by 7dir** [comment]
should maintainer closed it?

**Comment by datenimperator** [comment]
Just came across this. Is there a reason why this PR hasn't been merged for almost 18 months?

**Comment by jerome-diver** [comment]
sorry but something went wrong there, rails g scaffold with gem "sassc-rails" installed doesn't works with same error scss problem.
If this project is abandonned/deprecated, just tell it and we will forget it.
thank you for your great communication

**Comment by jerome-diver** [comment]
I see you are close this, but no communication has been made.
Could you find someone able to communicate something before to close please ?
it should be informative and nice

**Pull request closed without merging**
